apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todoapp
data:
  PYTHONUNBUFFERED: "1"
  SERVICEACCOUNT: "/var/run/secrets/kubernetes.io/serviceaccount"
  APISERVER: "https://kubernetes.default.svc"


